x-logging: &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"


services:
  server:
    build:
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    logging: *default-logging
